# Generated by Django 3.1.6 on 2021-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='high_score',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='result',
            name='mean_percentage',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='result',
            name='success_rate',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='result',
            name='total_students',
            field=models.IntegerField(default=75),
        ),
    ]
